### ISSUE TITLE
io.recieve_time() is failing

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CircuitPython_AdafruitIO#110]
CircuitPython version: `Adafruit CircuitPython 9.0.0-alpha.5 on 2023-11-15; Adafruit-Qualia-S3-RGB666 with ESP32S3`

i'm getting a repeated failure when calling `io.recieve_time()`:

```
Traceback (most recent call last):
  File "code.py", line 204, in <module>
  File "code.py", line 148, in update_time
  File "adafruit_io/adafruit_io.py", line 801, in receive_time
  File "adafruit_io/adafruit_io.py", line 565, in _get
  File "adafruit_requests.py", line 711, in get
  File "adafruit_requests.py", line 650, in request
  File "adafruit_requests.py", line 486, in _get_socket
gaierror: (-2, 'Name or service not known')

Code done running.
```

i have another project running on a matrixportal s3 (9.0.0-alpha.3 and now alpha.5) that started to fail around 7 PM saturday. i looked into it today when i was having the qualia issue and it is failing on `io.recieve_time()` with the same error. i also tried changing my IO key to see if that was possibly the problem but the issue persisted. all libraries were installed and updated from the latest circup.

**Comment by brentru** [comment]
@BlitzCityDIY  Nothing changed over the weekend, IO's MQTT server hasn't been bumped. Good that it's back up, let me know if it's having errors again and I'll re-open.
